#!/bin/bash -e
test -f ~/.emacs && echo "Found ~/.emacs" || (echo "create ~/.emacs" && touch ~/.emacs)
comstr=$(echo "(load-file \"$HOME/.dotfiles/config/emacs/emacs\") ;; Automatically generated by dotfiles")
cat ~/.emacs | grep "$comstr" >> /dev/null && echo "~/.emacs already include ~/.dotfiles/config/emacs/emacs" || (echo "Modifying ~/.emacs" && echo $comstr >> ~/.emacs)
sudo apt update
command -v emacs >> /dev/null || sudo apt install -y emacs
command -v python3 >> /dev/null || sudo apt install -y python3
command -v pip3 >> /dev/null || sudo apt install -y python3-pip
command -v python3 >> /dev/null && python3 -m venv --help >> /dev/null || sudo apt install -y python3-venv
command -v git >> /dev/null || sudo apt install -y git
command -v curl >> /dev/null || sudo apt install -y curl
# Note: Python packages (black, isort, flake8, pylint, mypy, pyright, jedi) 
# will be installed in virtual environments via requirements.txt
# PEP 668 prevents global installation of Python packages
