#!/usr/bin/env python3
#
#

import re
import sys

import pandas as pd

if len(sys.argv) < 1:
    print("ERROR: please give input log file.")
    sys.exit(1)

filein = sys.argv[1]
fileout = filein.replace("log", "csv")

with open(filein) as f:
    logs = f.readlines()

reg = r"^Executing:\s*([0-9]*)%\|.*\|\s*([0-9]+)/([0-9]+)\s*\[\s*([0-9\:]+)<([0-9\:]+)\s*,\s*([0-9\.]*).*cell.*\].*"

lines = []
for log in logs:
    linematch = re.findall(reg, log)
    if linematch:
        lines.append(linematch[0])

df = pd.DataFrame(
    lines,
    columns=[
        "progress",
        "i_cell",
        "n_cell",
        "time_processing",
        "time_remaing",
        "time_per_cell",
    ],
)
df.to_csv(fileout, index=False)
