#!/usr/bin/env bash
#
# Description:
#   Install Emacs and basic tooling via apt (Linux).
#   If admin/apt is not available, this script prints a message and exits successfully.
#
set -euo pipefail

if [ "${HAS_ADMIN:-0}" != "1" ]; then
  echo "No admin privileges available; skipping apt installs (emacs)."
  exit 0
fi

if ! command -v apt >/dev/null 2>&1; then
  echo "apt not available; skipping apt installs (emacs)."
  exit 0
fi

touch "$HOME/.emacs"
comstr="(load-file \"$HOME/.dotfiles/configs/emacs/emacs\") ;; Automatically generated by install.bash"
grep -F "$comstr" "$HOME/.emacs" >/dev/null 2>&1 || echo "$comstr" >> "$HOME/.emacs"

sudo apt update || true
command -v emacs >/dev/null 2>&1 || sudo apt install -y emacs || true
command -v python3 >/dev/null 2>&1 || sudo apt install -y python3 || true
command -v pip3 >/dev/null 2>&1 || sudo apt install -y python3-pip || true
python3 -m venv --help >/dev/null 2>&1 || sudo apt install -y python3-venv || true
command -v git >/dev/null 2>&1 || sudo apt install -y git || true
command -v curl >/dev/null 2>&1 || sudo apt install -y curl || true

