# Configuration for non-interactive bash shell

# Start here
export BASH_DOTFILES="${BASH_DOTFILES}:<${BASH_SOURCE}"

# Cleaning
alias c='rm -f *~'

# End here
export BASH_DOTFILES="${BASH_DOTFILES}:${BASH_SOURCE}>"

