# Configuration for interactive bash shell

# What changed?
pushd ~/.dotfiles > /dev/null
git status -s
popd > /dev/null

[[ ":$PATH:" != *":$HOME/.dotfiles/script:"* ]] && PATH="$HOME/.dotfiles/script:${PATH}"
