#!/bin/bash
test -f ~/.emacs && echo "Found ~/.emacs" || (echo "create ~/.emacs" && touch ~/.emacs)
comstr=$(echo "(load-file \"$HOME/.dotfiles/config/emacs/emacs\") ;; Automatically generated by dotfiles")
cat ~/.emacs | grep "$comstr" >> /dev/null && echo "~/.emacs already include ~/.dotfiles/config/emacs/emacs" || (echo "Modifying ~/.emacs" && echo $comstr >> ~/.emacs)
