#!/bin/bash

comstr='test -f ~/.dotfiles/config/bash/rc && . ~/.dotfiles/config/bash/rc # Automatically generated by setup.bash'
cat ~/.bashrc | grep "$comstr" >> /dev/null && echo "~/.bashrc already include ~/.dotfiles/config/bash/rc" || (echo "Modifying ~/.bashrc" && echo $comstr >> ~/.bashrc)

comstr='test -f ~/.dotfiles/config/bash/profile && . ~/.dotfiles/config/bash/profile # Automatically generated by setup.bash'
cat ~/.profile | grep "$comstr" >> /dev/null && echo "~/.profile already include ~/.dotfiles/config/bash/profile" || (echo "Modifying ~/.profile" && echo $comstr >> ~/.profile)
