#!/usr/bin/env bash
#
# Description:
#   Userland-only installation for Linux (Ubuntu/Debian/Fedora/Arch):
#   - Configure bash to source dotfiles configs
#   - Install userland tools (yq, miniconda) without requiring admin
#   - No system package installations (userland-only)
#
# Usage:
#   ./make/install_linux.bash
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "Linux install (userland-only, no admin required)"

###############################################################################
# Always: shell integration (bash)
###############################################################################
touch "$HOME/.bashrc" "$HOME/.profile"

line_rc='test -f ~/.dotfiles/configs/bash/rc && . ~/.dotfiles/configs/bash/rc # Automatically generated by install.bash'
line_profile='test -f ~/.dotfiles/configs/bash/profile && . ~/.dotfiles/configs/bash/profile # Automatically generated by install.bash'

grep -F "$line_rc" "$HOME/.bashrc" >/dev/null 2>&1 || echo "$line_rc" >> "$HOME/.bashrc"
grep -F "$line_profile" "$HOME/.profile" >/dev/null 2>&1 || echo "$line_profile" >> "$HOME/.profile"

###############################################################################
# Always: git global config (via [include])
###############################################################################
touch "$HOME/.gitconfig"
git_include="path = $HOME/.dotfiles/configs/git/gitconfig"
if ! git config --global --get-all include.path 2>/dev/null | grep -qF "$HOME/.dotfiles/configs/git/gitconfig"; then
  git config --global --add include.path "$HOME/.dotfiles/configs/git/gitconfig"
  echo "INFO: git global config linked via [include]."
fi

###############################################################################
# Optional: git aliases (env-controlled, legacy – kept for compatibility)
###############################################################################
if [ "${DOTFILES_SETUP_GIT_ALIASES:-0}" = "1" ]; then
  git config --global alias.co checkout
  git config --global alias.br branch
  git config --global alias.ci commit
  git config --global alias.st status
else
  echo "Skipping legacy git aliases (set DOTFILES_SETUP_GIT_ALIASES=1 to enable, or use configs/git/gitconfig)."
fi

###############################################################################
# Optional: VS Code config (if code is available)
###############################################################################
install_vscode_config() {
  if ! command -v code >/dev/null 2>&1; then
    echo "INFO: VS Code (code) not found; skipping VS Code config setup."
    return 0
  fi

  local vscode_user_dir="$HOME/.config/Code/User"
  mkdir -p "$vscode_user_dir"

  for cfg in settings.json keybindings.json; do
    local src="$REPO_ROOT/configs/vscode/$cfg"
    local dst="$vscode_user_dir/$cfg"
    if [ ! -f "$dst" ] && [ ! -L "$dst" ]; then
      ln -s "$src" "$dst"
      echo "INFO: VS Code $cfg linked."
    else
      echo "INFO: VS Code $cfg already exists; skipping (remove manually to re-link)."
    fi
  done

  if [ -f "$REPO_ROOT/configs/vscode/extensions.txt" ]; then
    echo "INFO: Installing VS Code extensions..."
    grep -v '^\s*#' "$REPO_ROOT/configs/vscode/extensions.txt" | grep -v '^\s*$' | while read -r ext; do
      code --install-extension "$ext" --force >/dev/null 2>&1 && echo "  installed: $ext" || echo "  WARNING: failed to install $ext"
    done
  fi
}
install_vscode_config || true

###############################################################################
# Optional: emacs config (if emacs is available)
###############################################################################
if command -v emacs >/dev/null 2>&1; then
  touch "$HOME/.emacs"
  emacs_load="(load-file \"$HOME/.dotfiles/configs/emacs/emacs\") ;; Automatically generated by install.bash"
  grep -F "$emacs_load" "$HOME/.emacs" >/dev/null 2>&1 || echo "$emacs_load" >> "$HOME/.emacs"
  echo "INFO: emacs found, configuration linked."
else
  echo "INFO: emacs not found. Install it manually if needed (userland: AppImage or from source)."
fi

###############################################################################
# Optional: yq install (userland, no admin required)
###############################################################################
install_yq() {
  local binary="yq_linux_amd64"
  local version="v4.43.1"
  local path_exe="$HOME/bin/yq_$version"

  mkdir -p "$HOME/bin"
  if [ -f "$path_exe" ]; then
    rm -f "$HOME/bin/yq" || true
    ln -s "$path_exe" "$HOME/bin/yq"
    return 0
  fi

  if ! command -v sha256sum >/dev/null 2>&1; then
    echo "WARNING: sha256sum not available; skipping yq install (cannot verify download integrity)." 1>&2
    return 0
  fi

  local asset="${binary}.tar.gz"
  local base_url="https://github.com/mikefarah/yq/releases/download/${version}"
  local tmpdir
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "$tmpdir"' RETURN

  if command -v wget >/dev/null 2>&1; then
    wget -q "${base_url}/${asset}" -O "${tmpdir}/${asset}"
    wget -q "${base_url}/checksums" -O "${tmpdir}/checksums"
  elif command -v curl >/dev/null 2>&1; then
    curl -fsSL "${base_url}/${asset}" -o "${tmpdir}/${asset}"
    curl -fsSL "${base_url}/checksums" -o "${tmpdir}/checksums"
  else
    echo "WARNING: neither wget nor curl found; skipping yq install." 1>&2
    return 0
  fi

  # yq checksums file: first column is filename, then hashes in order of checksums_hashes_order (SHA-256 is 18th algorithm = field 19).
  local expected_sha
  expected_sha="$(awk -v a="$asset" '$1==a {print $19; exit}' "${tmpdir}/checksums" | tr -d '\r')"
  if [ -z "${expected_sha}" ] || [ "${#expected_sha}" -ne 64 ]; then
    echo "WARNING: unable to find SHA256 checksum for ${asset}; skipping yq install." 1>&2
    return 0
  fi

  echo "${expected_sha}  ${tmpdir}/${asset}" | sha256sum -c - >/dev/null

  tar -xzf "${tmpdir}/${asset}" -C "${tmpdir}"
  mv "${tmpdir}/${binary}" "$path_exe"
  rm -f "$HOME/bin/yq" || true
  ln -s "$path_exe" "$HOME/bin/yq"
}
install_yq || true

###############################################################################
# Optional: miniconda install (userland, no admin required)
###############################################################################
install_miniconda() {
  if [ "${DOTFILES_INSTALL_MINICONDA:-0}" != "1" ]; then
    echo "Skipping Miniconda install by default (set DOTFILES_INSTALL_MINICONDA=1 to enable)."
    return 0
  fi

  local base="https://repo.anaconda.com/miniconda"
  local arch
  arch="$(uname -m 2>/dev/null || echo unknown)"
  local file
  case "$arch" in
    x86_64|amd64) file="Miniconda3-latest-Linux-x86_64.sh" ;;
    aarch64|arm64) file="Miniconda3-latest-Linux-aarch64.sh" ;;
    *)
      echo "WARNING: unsupported architecture for miniconda ($arch); skipping miniconda install." 1>&2
      return 0
      ;;
  esac
  local url="${base}/${file}"
  if command -v conda >/dev/null 2>&1; then
    echo "conda already installed"
    return 0
  fi

  if ! command -v sha256sum >/dev/null 2>&1; then
    echo "WARNING: sha256sum not available; skipping miniconda install (cannot verify download integrity)." 1>&2
    return 0
  fi

  local root="${ROOT_MINICONDA:-$HOME/.miniconda3}"
  mkdir -p "$root"
  local installer="$root/install.sh"

  if [ -f "$installer" ] && [ "$(wc -l "$installer" | awk '{print $1}')" -eq 0 ]; then
    echo "WARNING: empty installer at $installer, removing."
    rm -f "$installer"
  fi

  if [ ! -f "$installer" ]; then
    if command -v wget >/dev/null 2>&1; then
      wget -q "$url" -O "$installer"
    elif command -v curl >/dev/null 2>&1; then
      curl -fsSL "$url" -o "$installer"
    else
      echo "WARNING: neither wget nor curl found; skipping miniconda install." 1>&2
      return 0
    fi
  fi

  # Verify installer integrity against the official SHA256 listed in the Miniconda index.
  # Source: https://repo.anaconda.com/miniconda/ (HTML table: Filename, Size, Last Modified, SHA256)
  local expected_sha
  expected_sha="$(
    (curl -fsSL "${base}/" 2>/dev/null || wget -qO- "${base}/" 2>/dev/null || true) \
      | grep -A3 ">${file}</a>" | tail -1 | sed -n 's/.*<td>\([a-f0-9]\{64\}\)<\/td>.*/\1/p'
  )"
  if [ -n "${expected_sha}" ]; then
    echo "${expected_sha}  ${installer}" | sha256sum -c - >/dev/null || {
      echo "WARNING: SHA256 checksum mismatch for ${file}; installer may be corrupted." 1>&2
      return 0
    }
  else
    echo "WARNING: unable to fetch official SHA256 for ${file}; refusing to run unverified installer." 1>&2
    return 0
  fi

  bash "$installer" -b -u -p "$root"
  "$root/bin/conda" init || true
  "$root/bin/conda" config --set auto_activate_base false || true
}
install_miniconda || true

echo "Linux install completed (userland-only)."
