#!/usr/bin/env bash
#
# Description:
#   Bare installation for Ubuntu:
#   - Configure bash to source dotfiles configs
#   - Optionally install packages via apt (if admin privileges are available)
#   - Optionally install userland tools (yq, miniconda) without requiring admin
#
# Usage:
#   ./make/install_bare-ubuntu.bash
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

check_admin() {
  # True if we can run privileged commands (root or passwordless sudo).
  if [ "$(id -u)" -eq 0 ]; then
    return 0
  fi
  if command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

HAS_ADMIN=0
if check_admin; then
  HAS_ADMIN=1
else
  echo "INFO: Admin privileges not available; will skip privileged installs."
fi
export HAS_ADMIN

HAS_APT=0
if command -v apt >/dev/null 2>&1; then
  HAS_APT=1
fi

echo "Ubuntu bare install (HAS_ADMIN=$HAS_ADMIN, HAS_APT=$HAS_APT)"

###############################################################################
# Always: shell integration (bash)
###############################################################################
touch "$HOME/.bashrc" "$HOME/.profile"

line_rc='test -f ~/.dotfiles/configs/bash/rc && . ~/.dotfiles/configs/bash/rc # Automatically generated by install.bash'
line_profile='test -f ~/.dotfiles/configs/bash/profile && . ~/.dotfiles/configs/bash/profile # Automatically generated by install.bash'

grep -F "$line_rc" "$HOME/.bashrc" >/dev/null 2>&1 || echo "$line_rc" >> "$HOME/.bashrc"
grep -F "$line_profile" "$HOME/.profile" >/dev/null 2>&1 || echo "$line_profile" >> "$HOME/.profile"

###############################################################################
# Optional: git aliases (env-controlled)
###############################################################################
if [ "${DOTFILES_SETUP_GIT_ALIASES:-0}" = "1" ]; then
  git config --global alias.co checkout
  git config --global alias.br branch
  git config --global alias.ci commit
  git config --global alias.st status
else
  echo "Skipping git aliases (set DOTFILES_SETUP_GIT_ALIASES=1 to enable)."
fi

###############################################################################
# Optional: apt installs (non-fatal without admin)
###############################################################################
if [ "$HAS_ADMIN" = "1" ] && [ "$HAS_APT" = "1" ]; then
  # Emacs + small baseline tools
  touch "$HOME/.emacs"
  emacs_load="(load-file \"$HOME/.dotfiles/configs/emacs/emacs\") ;; Automatically generated by install.bash"
  grep -F "$emacs_load" "$HOME/.emacs" >/dev/null 2>&1 || echo "$emacs_load" >> "$HOME/.emacs"

  sudo apt update || true
  command -v emacs >/dev/null 2>&1 || sudo apt install -y emacs || true
  command -v python3 >/dev/null 2>&1 || sudo apt install -y python3 || true
  command -v pip3 >/dev/null 2>&1 || sudo apt install -y python3-pip || true
  python3 -m venv --help >/dev/null 2>&1 || sudo apt install -y python3-venv || true
  command -v git >/dev/null 2>&1 || sudo apt install -y git || true
  command -v curl >/dev/null 2>&1 || sudo apt install -y curl || true

  # virtualenvwrapper (only if not already installed)
  if ! command -v workon >/dev/null 2>&1; then
    packages=(python3-virtualenvwrapper virtualenvwrapper virtualenvwrapper-doc)
    for package in "${packages[@]}"; do
      if ! dpkg -l "$package" &>/dev/null; then
        echo "Installing package: $package"
        sudo apt install -y "$package" || true
      fi
    done

    # Ensure config block exists in ~/.bashrc
    VENVWRAPPER_CONFIG="$(cat <<'EOF'
# START setup-virtualenvwrapper.bash
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/project
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
# END setup-virtualenvwrapper.bash
EOF
)"

    if grep -q "# START setup-virtualenvwrapper.bash" "$HOME/.bashrc"; then
      sed -i '/# START setup-virtualenvwrapper.bash/,/# END setup-virtualenvwrapper.bash/d' "$HOME/.bashrc" || true
    fi
    echo "$VENVWRAPPER_CONFIG" >> "$HOME/.bashrc"
  fi
else
  echo "Admin or apt not available; skipping apt-based installs."
fi

###############################################################################
# Optional: yq install (userland, no admin required)
###############################################################################
install_yq() {
  local binary="yq_linux_amd64"
  local version="v4.43.1"
  local path_exe="$HOME/bin/yq_$version"

  mkdir -p "$HOME/bin"
  if [ -f "$path_exe" ]; then
    rm -f "$HOME/bin/yq" || true
    ln -s "$path_exe" "$HOME/bin/yq"
    return 0
  fi

  if ! command -v sha256sum >/dev/null 2>&1; then
    echo "WARNING: sha256sum not available; skipping yq install (cannot verify download integrity)." 1>&2
    return 0
  fi

  local asset="${binary}.tar.gz"
  local base_url="https://github.com/mikefarah/yq/releases/download/${version}"
  local tmpdir
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "$tmpdir"' RETURN

  if command -v wget >/dev/null 2>&1; then
    wget -q "${base_url}/${asset}" -O "${tmpdir}/${asset}"
    wget -q "${base_url}/checksums" -O "${tmpdir}/checksums"
  elif command -v curl >/dev/null 2>&1; then
    curl -fsSL "${base_url}/${asset}" -o "${tmpdir}/${asset}"
    curl -fsSL "${base_url}/checksums" -o "${tmpdir}/checksums"
  else
    echo "WARNING: neither wget nor curl found; skipping yq install." 1>&2
    return 0
  fi

  local expected_sha
  expected_sha="$(awk -v a="$asset" '$2==a {print $1; exit}' "${tmpdir}/checksums" | tr -d '\r')"
  if [ -z "${expected_sha}" ]; then
    echo "WARNING: unable to find checksum for ${asset}; skipping yq install." 1>&2
    return 0
  fi

  echo "${expected_sha}  ${tmpdir}/${asset}" | sha256sum -c - >/dev/null

  tar -xzf "${tmpdir}/${asset}" -C "${tmpdir}"
  mv "${tmpdir}/${binary}" "$path_exe"
  rm -f "$HOME/bin/yq" || true
  ln -s "$path_exe" "$HOME/bin/yq"
}
install_yq || true

###############################################################################
# Optional: miniconda install (userland, no admin required)
###############################################################################
install_miniconda() {
  local base="https://repo.anaconda.com/miniconda"
  local arch
  arch="$(uname -m 2>/dev/null || echo unknown)"
  local file
  case "$arch" in
    x86_64|amd64) file="Miniconda3-latest-Linux-x86_64.sh" ;;
    aarch64|arm64) file="Miniconda3-latest-Linux-aarch64.sh" ;;
    *)
      echo "WARNING: unsupported architecture for miniconda ($arch); skipping miniconda install." 1>&2
      return 0
      ;;
  esac
  local url="${base}/${file}"
  if command -v conda >/dev/null 2>&1; then
    echo "conda already installed"
    return 0
  fi

  if ! command -v sha256sum >/dev/null 2>&1; then
    echo "WARNING: sha256sum not available; skipping miniconda install (cannot verify download integrity)." 1>&2
    return 0
  fi

  local root="${ROOT_MINICONDA:-$HOME/.miniconda3}"
  mkdir -p "$root"
  local installer="$root/install.sh"

  if [ -f "$installer" ] && [ "$(wc -l "$installer" | awk '{print $1}')" -eq 0 ]; then
    echo "WARNING: empty installer at $installer, removing."
    rm -f "$installer"
  fi

  if [ ! -f "$installer" ]; then
    if command -v wget >/dev/null 2>&1; then
      wget -q "$url" -O "$installer"
    elif command -v curl >/dev/null 2>&1; then
      curl -fsSL "$url" -o "$installer"
    else
      echo "WARNING: neither wget nor curl found; skipping miniconda install." 1>&2
      return 0
    fi
  fi

  # Verify installer integrity against the official SHA256 listed in the Miniconda index.
  # Source: https://repo.anaconda.com/miniconda/
  local expected_sha
  expected_sha="$(
    (curl -fsSL "${base}/" 2>/dev/null || wget -qO- "${base}/" 2>/dev/null || true) \
      | awk -F'|' -v f="$file" '$1 ~ "\\[" f "\\]" {gsub(/^[[:space:]]+|[[:space:]]+$/, "", $4); print $4; exit}'
  )"
  if [ -z "${expected_sha}" ]; then
    echo "WARNING: unable to fetch official SHA256 for ${file}; skipping miniconda install." 1>&2
    return 0
  fi

  echo "${expected_sha}  ${installer}" | sha256sum -c - >/dev/null

  bash "$installer" -b -u -p "$root"
  "$root/bin/conda" init || true
  "$root/bin/conda" config --set auto_activate_base false || true
}
install_miniconda || true

echo "Bare install completed."

