#!/usr/bin/env zsh
#
# Description:
#   Minimal (bare) installation for macOS:
#   - Add sourcing lines to ~/.zshrc and ~/.zprofile
#
# Usage:
#   ./make/install_macos.zsh
#
set -euo pipefail

line_rc='test -f ~/.dotfiles/configs/zsh/rc && source ~/.dotfiles/configs/zsh/rc # Automatically generated by install.bash'
line_profile='test -f ~/.dotfiles/configs/zsh/profile && source ~/.dotfiles/configs/zsh/profile # Automatically generated by install.bash'

touch "$HOME/.zshrc" "$HOME/.zprofile"

grep -F "$line_rc" "$HOME/.zshrc" >/dev/null 2>&1 || echo "$line_rc" >> "$HOME/.zshrc"
grep -F "$line_profile" "$HOME/.zprofile" >/dev/null 2>&1 || echo "$line_profile" >> "$HOME/.zprofile"

echo "macOS install completed."

