#!/usr/bin/env bash
#
# Description:
#   Bare installation for Linux:
#   - Configure bash to source dotfiles configs
#   - Optionally install packages via apt (if admin privileges are available)
#   - Optionally install userland tools (yq, miniconda) without requiring admin
#
# Usage:
#   ./make/install_bare-linux.bash
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

check_admin() {
  # True if we can run privileged commands (root or passwordless sudo).
  if [ "$(id -u)" -eq 0 ]; then
    return 0
  fi
  if command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

HAS_ADMIN=0
if check_admin; then
  HAS_ADMIN=1
else
  echo "INFO: Admin privileges not available; will skip privileged installs."
fi
export HAS_ADMIN

HAS_APT=0
if command -v apt >/dev/null 2>&1; then
  HAS_APT=1
fi

echo "Linux bare install (HAS_ADMIN=$HAS_ADMIN, HAS_APT=$HAS_APT)"

###############################################################################
# Always: shell integration (bash)
###############################################################################
touch "$HOME/.bashrc" "$HOME/.profile"

line_rc='test -f ~/.dotfiles/configs/bash/rc && . ~/.dotfiles/configs/bash/rc # Automatically generated by install.bash'
line_profile='test -f ~/.dotfiles/configs/bash/profile && . ~/.dotfiles/configs/bash/profile # Automatically generated by install.bash'

grep -F "$line_rc" "$HOME/.bashrc" >/dev/null 2>&1 || echo "$line_rc" >> "$HOME/.bashrc"
grep -F "$line_profile" "$HOME/.profile" >/dev/null 2>&1 || echo "$line_profile" >> "$HOME/.profile"

###############################################################################
# Optional: git aliases (env-controlled)
###############################################################################
if [ "${DOTFILES_SETUP_GIT_ALIASES:-0}" = "1" ]; then
  git config --global alias.co checkout
  git config --global alias.br branch
  git config --global alias.ci commit
  git config --global alias.st status
else
  echo "Skipping git aliases (set DOTFILES_SETUP_GIT_ALIASES=1 to enable)."
fi

###############################################################################
# Optional: apt installs (non-fatal without admin)
###############################################################################
if [ "$HAS_ADMIN" = "1" ] && [ "$HAS_APT" = "1" ]; then
  # Emacs + small baseline tools
  touch "$HOME/.emacs"
  emacs_load="(load-file \"$HOME/.dotfiles/configs/emacs/emacs\") ;; Automatically generated by install.bash"
  grep -F "$emacs_load" "$HOME/.emacs" >/dev/null 2>&1 || echo "$emacs_load" >> "$HOME/.emacs"

  sudo apt update || true
  command -v emacs >/dev/null 2>&1 || sudo apt install -y emacs || true
  command -v python3 >/dev/null 2>&1 || sudo apt install -y python3 || true
  command -v pip3 >/dev/null 2>&1 || sudo apt install -y python3-pip || true
  python3 -m venv --help >/dev/null 2>&1 || sudo apt install -y python3-venv || true
  command -v git >/dev/null 2>&1 || sudo apt install -y git || true
  command -v curl >/dev/null 2>&1 || sudo apt install -y curl || true

  # virtualenvwrapper (only if not already installed)
  if ! command -v workon >/dev/null 2>&1; then
    packages=(python3-virtualenvwrapper virtualenvwrapper virtualenvwrapper-doc)
    for package in "${packages[@]}"; do
      if ! dpkg -l "$package" &>/dev/null; then
        echo "Installing package: $package"
        sudo apt install -y "$package" || true
      fi
    done

    # Ensure config block exists in ~/.bashrc
    read -r -d '' VENVWRAPPER_CONFIG << 'EOF'
# START setup-virtualenvwrapper.bash
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/project
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
# END setup-virtualenvwrapper.bash
EOF

    if grep -q "# START setup-virtualenvwrapper.bash" "$HOME/.bashrc"; then
      sed -i '/# START setup-virtualenvwrapper.bash/,/# END setup-virtualenvwrapper.bash/d' "$HOME/.bashrc" || true
    fi
    echo "$VENVWRAPPER_CONFIG" >> "$HOME/.bashrc"
  fi
else
  echo "Admin or apt not available; skipping apt-based installs."
fi

###############################################################################
# Optional: yq install (userland, no admin required)
###############################################################################
install_yq() {
  local binary="yq_linux_amd64"
  local version="v4.43.1"
  local path_exe="$HOME/bin/yq_$version"

  mkdir -p "$HOME/bin"
  if [ -f "$path_exe" ]; then
    rm -f "$HOME/bin/yq" || true
    ln -s "$path_exe" "$HOME/bin/yq"
    return 0
  fi

  if command -v wget >/dev/null 2>&1; then
    wget "https://github.com/mikefarah/yq/releases/download/${version}/${binary}.tar.gz" -O - | tar xz
  elif command -v curl >/dev/null 2>&1; then
    curl -fsSL "https://github.com/mikefarah/yq/releases/download/${version}/${binary}.tar.gz" | tar xz
  else
    echo "WARNING: neither wget nor curl found; skipping yq install." 1>&2
    return 0
  fi
  mv "$binary" "$path_exe"
  rm -f "$HOME/bin/yq" || true
  ln -s "$path_exe" "$HOME/bin/yq"
}
install_yq || true

###############################################################################
# Optional: miniconda install (userland, no admin required)
###############################################################################
install_miniconda() {
  local url="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
  if command -v conda >/dev/null 2>&1; then
    echo "conda already installed"
    return 0
  fi

  local root="${ROOT_MINICONDA:-$HOME/.miniconda3}"
  mkdir -p "$root"
  local installer="$root/install.sh"

  if [ -f "$installer" ] && [ "$(wc -l "$installer" | awk '{print $1}')" -eq 0 ]; then
    echo "WARNING: empty installer at $installer, removing."
    rm -f "$installer"
  fi

  if [ ! -f "$installer" ]; then
    if command -v wget >/dev/null 2>&1; then
      wget "$url" -O "$installer"
    elif command -v curl >/dev/null 2>&1; then
      curl -fsSL "$url" -o "$installer"
    else
      echo "WARNING: neither wget nor curl found; skipping miniconda install." 1>&2
      return 0
    fi
  fi

  bash "$installer" -b -u -p "$root"
  "$root/bin/conda" init || true
  "$root/bin/conda" config --set auto_activate_base false || true
}
install_miniconda || true

echo "Bare install completed."

