#!/usr/bin/env bash
#
# Description:
#   Uninstall dotfiles shell integration by removing the lines added by installers.
#   This is safe and idempotent (it does not delete user data by default).
#
# Usage:
#   ./make/uninstall.bash
#
set -euo pipefail

remove_line() {
  local file="$1"
  local marker="$2"
  if [ -f "$file" ]; then
    # Remove exact marker lines (GNU sed). On macOS, use `gsed` if needed.
    sed -i "\|$marker|d" "$file" 2>/dev/null || true
  fi
}

marker_rc='test -f ~/.dotfiles/configs/bash/rc && . ~/.dotfiles/configs/bash/rc # Automatically generated by install.bash'
marker_profile='test -f ~/.dotfiles/configs/bash/profile && . ~/.dotfiles/configs/bash/profile # Automatically generated by install.bash'
marker_zshrc='test -f ~/.dotfiles/configs/zsh/rc && source ~/.dotfiles/configs/zsh/rc # Automatically generated by install.bash'
marker_zprofile='test -f ~/.dotfiles/configs/zsh/profile && source ~/.dotfiles/configs/zsh/profile # Automatically generated by install.bash'

remove_line "$HOME/.bashrc" "$marker_rc"
remove_line "$HOME/.profile" "$marker_profile"
remove_line "$HOME/.zshrc" "$marker_zshrc"
remove_line "$HOME/.zprofile" "$marker_zprofile"

echo "Uninstall completed (shell init lines removed where present)."

