#!/usr/bin/env bash
#
# Description:
#   Add dotfiles bash config to the user's shell init files (idempotent).
#
set -euo pipefail

touch "$HOME/.bashrc" "$HOME/.profile"

line_rc='test -f ~/.dotfiles/configs/bash/rc && . ~/.dotfiles/configs/bash/rc # Automatically generated by install.bash'
line_profile='test -f ~/.dotfiles/configs/bash/profile && . ~/.dotfiles/configs/bash/profile # Automatically generated by install.bash'

grep -F "$line_rc" "$HOME/.bashrc" >/dev/null 2>&1 || echo "$line_rc" >> "$HOME/.bashrc"
grep -F "$line_profile" "$HOME/.profile" >/dev/null 2>&1 || echo "$line_profile" >> "$HOME/.profile"

