#!/bin/bash -e
#
# Find all modified IPYNB and clear there output.
#
##
IPYNB_FILES=()
while IFS='' read -r line; do
    IPYNB_FILES+=( "$line" ); 
    # finding all staged *.ipynb files added, copied, modified or renamed since last commit
done < <(git diff-index --name-only --cached --diff-filter=ACMR "${against}" -- | grep -i \.ipynb$ )
for FILE in "${IPYNB_FILES[@]}"; do
    echo "Processing file: '$FILE'"
    # you may need to provide the full path to 'jupyter' executable
    # if it is not in the path
    jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "$FILE"
    # echo "Current EXIT_CODE value: $?"
done
