#!/bin/bash -e

function helpme() {
    echo ""
    echo "Convert a Jupyter Notebook to PDF without code."
    echo ""
    echo "See also: jrun, jstart."
    echo ""
    echo "From: https://ga7g08.github.io/2015/06/25/ipython-nbconvert-latex-template-to-hide-code"
    echo ""
}

#
if [ -z "$1" ];then
    echo "ERROR: please provide path to jupyter notebook."
    helpme
    exit 1
elif [ "$1" == "--help" ] || [ "$1" == "-h" ];then
    helpme
    exit 0
fi
jupy=$(basename $1)
dir=$(dirname $1)
pushd $dir > /dev/null
cat > hidecode.tplx <<EOF
((*- extends 'article.tplx' -*))
((* block input_group *))
    ((*- if cell.metadata.get('nbconvert', {}).get('show_code', False) -*))
         ((( super() )))
    ((*- endif -*))
((* endblock input_group *))
EOF
ipython nbconvert --to pdf --template hidecode $jupy
rm -f hidecode.tplx
popd > /dev/null
