#!/bin/bash -e

function helpme() {
    echo ""
    echo "Run a Jupyter notebook in batch and output result in HTML."
    echo "Use environement variable NOTEBOOK_BATCH."
    echo ""
    echo "See also: jpdf, jstart."
    echo ""
}

#
if [ -z "$1" ];then
    echo "ERROR: please provide path to jupyter notebook."
    helpme
    exit 1
elif [ "$1" == "--help" ] || [ "$1" == "-h" ];then
    helpme
    exit 0
else
    nb_in="$1"
fi
nb_out=$(echo $nb_in | awk -F".ipynb" '{print $1}').out.ipynb

export NOTEBOOK_BATCH=1
if [ -n "$(command -v papermill)" ];then
    echo "Using papermill"
    papermill --version
    papermill  --request-save-on-cell-execute --log-output --report-mode --progress-bar $nb_in $nb_out
else
    echo "Using jupyter nbconvert"
    jupyter nbconvert --version
    jupyter nbconvert --to notebook --execute $nb_in --output $nb_out
fi
jupyter nbconvert --to html $nb_out
