#!/bin/bash -e
#
# Description wrapper for jstart.py
#
##
function helpme() {
    echo ""
    echo "Run a Jupyter notebook in batch and output result in HTML."
    echo "Use environement variable NOTEBOOK_BATCH."
    echo ""
    echo "See also: jpdf, jstart."
    echo ""
}
. $WORKON_HOME/eda/bin/activate
python $HOME/.dotfiles/script/python3/jstart.py
