#!/bin/bash -e

echo "GIT configuration"
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status

echo "Include rc configuration in .bashrc"
comstr='test -f ~/.dotfiles/config/bash/rc && . ~/.dotfiles/config/bash/rc # Automatically generated by setup.bash'
cat ~/.bashrc | grep "$comstr" >> /dev/null && echo "~/.bashrc already include ~/.dotfiles/config/bash/rc" || (echo "Modifying ~/.bashrc" && echo $comstr >> ~/.bashrc)

echo "Include profile configuration in .profile"
comstr='test -f ~/.dotfiles/config/bash/profile && . ~/.dotfiles/config/bash/profile # Automatically generated by setup.bash'
cat ~/.profile | grep "$comstr" >> /dev/null && echo "~/.profile already include ~/.dotfiles/config/bash/profile" || (echo "Modifying ~/.profile" && echo $comstr >> ~/.profile)

echo "Include emacs configuration in .emacs"
comstr=$(echo "(load-file \"$HOME/.dotfiles/config/emacs/emacs\") ;; Automatically generated by dotfiles")
cat ~/.emacs | grep "$comstr" >> /dev/null && echo "~/.emacs already include ~/.dotfiles/config/emacs/emacs" || (echo "Modifying ~/.emacs" && echo $comstr >> ~/.emacs)
